--- CREATE DATABASE ---
CREATE DATABASE DW_Staging;
GO
USE DW_Staging;

--- CREATE SCHEMA ---
CREATE SCHEMA Stage;
GO

--- CREATE TABLES ---
CREATE TABLE Stage.Clinic_ADMISSIONS (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT NOT NULL,
    ADMIT_TIME DATETIME NOT NULL,
    DISCH_TIME DATETIME NOT NULL,
    ADMISSION_TYPE VARCHAR(50) NOT NULL,
    ADMISSION_LOCATION VARCHAR(50) NOT NULL,
    DISCHARGE_LOCATION VARCHAR(50) NOT NULL,
    INSURANCE VARCHAR(255) NOT NULL,
    ETHNICITY VARCHAR(200) NOT NULL,
    DIAGNOSIS VARCHAR(255),
    HOSPITAL_EXPIRE_FLAG SMALLINT,
    CONSTRAINT pk_stage_clinic_admissions PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.Clinic_CALLOUT (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT NOT NULL,
    SUBMIT_WARD_ID INT,
    SUBMIT_CARE_UNIT VARCHAR(15),
    CURR_WARD_ID INT,
    CURR_CARE_UNIT VARCHAR(15),
    CALLOUT_WARD_ID INT,
    CALLOUT_SERVICE VARCHAR(10) NOT NULL,
    CALLOUT_STATUS VARCHAR(20) NOT NULL,
    CALLOUT_OUTCOME VARCHAR(20) NOT NULL,
    DISCHARGE_WARD_ID INT,
    ACKNOWLEDGE_STATUS VARCHAR(20) NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    UPDATE_TIME DATETIME NOT NULL,
    ACKNOWLEDGE_TIME DATETIME,
    OUTCOME_TIME DATETIME NOT NULL,
    FIRST_RESERVATION_TIME DATETIME,
    CURRENT_RESERVATION_TIME DATETIME,
    CONSTRAINT pk_stage_clinic_callout PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.Clinic_DIAGNOSES_ICD (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT NOT NULL,
    SEQ_NUM INT,
    ICD9_CODE VARCHAR(10),
    CONSTRAINT pk_stage_clinic_diagnoses_icd PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.Clinic_D_ICD_DIAGNOSES (
    ROW_ID INT NOT NULL,
    ICD9_CODE VARCHAR(10) NOT NULL,
    SHORT_TITLE VARCHAR(50) NOT NULL,
    LONG_TITLE VARCHAR(255) NOT NULL,
    CONSTRAINT pk_stage_clinic_d_icd_diagnoses PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.Clinic_PATIENTS (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    GENDER VARCHAR(5) NOT NULL,
    DOB DATETIME,
    DOD DATETIME,
    EXPIRE_FLAG INT NOT NULL,
    CONSTRAINT pk_stage_clinic_patients PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.Clinic_SERVICES (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT NOT NULL,
    TRANSFER_TIME DATETIME NOT NULL,
    PREV_SERVICE VARCHAR(20),
    CURR_SERVICE VARCHAR(20),
    CONSTRAINT pk_stage_clinic_services PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.Clinic_TRANSFERS (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT NOT NULL,
    ICU_STAY_ID INT,
    DB_SOURCE VARCHAR(20),
    EVENT_TYPE VARCHAR(20),
    PREV_CAREUNIT VARCHAR(20),
    CURR_CAREUNIT VARCHAR(20),
    PREV_WARD_ID SMALLINT,
    CURR_WARD_ID SMALLINT,
    IN_TIME DATETIME,
    OUT_TIME DATETIME,
    LOS DOUBLE PRECISION,
    CONSTRAINT pk_stage_clinic_transfers PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.ICU_CAREGIVERS (
    ROW_ID INT NOT NULL,
    CG_ID INT NOT NULL,
    LABEL VARCHAR(15),
    [DESCRIPTION] VARCHAR(30),
    CONSTRAINT pk_stage_icu_caregivers PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.ICU_D_ITEMS (
    ROW_ID INT NOT NULL,
    ITEM_ID INT NOT NULL,
    LABEL VARCHAR(200),
    ABBREVIATION VARCHAR(100),
    DB_SOURCE VARCHAR(20),
    CATEGORY VARCHAR(100),
    UNIT_NAME VARCHAR(100),
    PARAM_TYPE VARCHAR(30),
    CONSTRAINT pk_stage_icu_d_items PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.ICU_STAYS (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT NOT NULL,
    ICU_STAY_ID INT NOT NULL,
    DB_SOURCE VARCHAR(20) NOT NULL,
    FIRST_CARE_UNIT VARCHAR(20) NOT NULL,
    LAST_CARE_UNIT VARCHAR(20) NOT NULL,
    FIRST_WARD_ID SMALLINT NOT NULL,
    LAST_WARD_ID SMALLINT NOT NULL,
    IN_TIME DATETIME NOT NULL,
    OUT_TIME DATETIME,
    LOS DOUBLE PRECISION,
    CONSTRAINT pk_stage_icu_icu_stays PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.ICU_INPUT_EVENTS_CV (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT,
    ICU_STAY_ID INT,
    CHART_TIME DATETIME,
    ITEM_ID INT,
    AMOUNT DOUBLE PRECISION,
    AMOUNT_UOM VARCHAR(30),
    RATE DOUBLE PRECISION,
    RATE_UOM VARCHAR(30),
    CG_ID INT,
    CONSTRAINT pk_stage_icu_input_events_cv PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.ICU_INPUT_EVENTS_MV (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT,
    ICU_STAY_ID INT,
    START_TIME DATETIME,
    END_TIME DATETIME,
    ITEM_ID INT,
    AMOUNT DOUBLE PRECISION,
    AMOUNT_UOM VARCHAR(30),
    RATE DOUBLE PRECISION,
    RATE_UOM VARCHAR(30),
    CG_ID INT,
    PATIENT_WEIGHT DOUBLE PRECISION,
    TOTAL_AMOUNT DOUBLE PRECISION,
    TOTAL_AMOUNT_UOM VARCHAR(50),
    CONSTRAINT pk_stage_icu_input_events_mv PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.ICU_OUTPUT_EVENTS (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT,
    ICU_STAY_ID INT,
    CHART_TIME DATETIME,
    ITEM_ID INT,
    [VALUE] DOUBLE PRECISION,
    VALUE_UOM VARCHAR(30),
    CG_ID INT,
    CONSTRAINT pk_stage_icu_output_events PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.ICU_PROCEDURE_EVENTS_MV (
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT NOT NULL,
    ICU_STAY_ID INT,
    START_TIME DATETIME,
    END_TIME DATETIME,
    ITEM_ID INT,
    [VALUE] DOUBLE PRECISION,
    VALUE_UOM VARCHAR(30),
    [LOCATION] VARCHAR(30),
    LOCATION_CATEGORY VARCHAR(30),
    CG_ID INT,
    CONSTRAINT pk_stage_icu_procedure_events_mv PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.D_LAB_ITEMS (
  	ROW_ID INT NOT NULL,
	ITEM_ID INT NOT NULL,
	LABEL VARCHAR(100) NOT NULL,
	FLUID VARCHAR(100) NOT NULL,
	CATEGORY VARCHAR(100) NOT NULL,
	LOINC_CODE VARCHAR(100),
	CONSTRAINT dlabitems_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Stage.LAB_EVENTS (
  	ROW_ID INT NOT NULL,
	PATIENT_ID INT NOT NULL,
	ADMISSION_ID INT,
	ITEM_ID INT NOT NULL,
	CHART_TIME DATETIME,
    [VALUE] VARCHAR(200),
	VALUE_NUM DOUBLE PRECISION,
	VALUE_UOM VARCHAR(20),
	FLAG VARCHAR(20),
	CONSTRAINT labevents_rowid_pk PRIMARY KEY (ROW_ID)
);
