-- INCREMENTAL LOAD: Clinic ADMISSIONS (Filtering by ADMIT_TIME)
DECLARE @LastAdmitTime DATETIME;

SELECT @LastAdmitTime = ISNULL(MAX(ADMIT_TIME), '2001-01-01') 
FROM Stage.Clinic_ADMISSIONS;

INSERT INTO Stage.Clinic_ADMISSIONS (
    ROW_ID, SUBJECT_ID, HADM_ID, ADMIT_TIME, DISCH_TIME, 
    ADMISSION_TYPE, ADMISSION_LOCATION, DISCHARGE_LOCATION, INSURANCE, 
    ETHNICITY, DIAGNOSIS, HOSPITAL_EXPIRE_FLAG
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, ADMIT_TIME, DISCH_TIME, 
    ADMISSION_TYPE, ADMISSION_LOCATION, DISCHARGE_LOCATION, INSURANCE, 
    ETHNICITY, DIAGNOSIS, HOSPITAL_EXPIRE_FLAG
FROM Hospital.Clinic.ADMISSIONS
WHERE ADMIT_TIME > @LastAdmitTime;


-- INCREMENTAL LOAD: Clinic DIAGNOSES_ICD (Filtering by ROW_ID)
DECLARE @MaxDiagRowID INT;

SELECT @MaxDiagRowID = ISNULL(MAX(ROW_ID), 0) 
FROM Stage.Clinic_DIAGNOSES_ICD;

INSERT INTO Stage.Clinic_DIAGNOSES_ICD (
    ROW_ID, SUBJECT_ID, HADM_ID, SEQ_NUM, ICD9_CODE
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, SEQ_NUM, ICD9_CODE
FROM Hospital.Clinic.DIAGNOSES_ICD
WHERE ROW_ID > @MaxDiagRowID;


-- INCREMENTAL LOAD: ICU DATETIME_EVENTS (Filtering by CHART_TIME)
DECLARE @LastChartTime DATETIME;

SELECT @LastChartTime = ISNULL(MAX(CHART_TIME), '2001-01-01') 
FROM Stage.ICU_DATETIME_EVENTS;

INSERT INTO Stage.ICU_DATETIME_EVENTS (
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, ITEM_ID, CHART_TIME, 
    CG_ID, [VALUE]
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, ITEM_ID, CHART_TIME, 
    CG_ID, [VALUE]
FROM Hospital.ICU.DATETIME_EVENTS
WHERE CHART_TIME > @LastChartTime;

-- INCREMENTAL LOAD: ICU INPUT_EVENTS_MV (Filtering by START_TIME)
DECLARE @LastInputStartTime DATETIME;

SELECT @LastInputStartTime = ISNULL(MAX(START_TIME), '2001-01-01') 
FROM Stage.ICU_INPUT_EVENTS_MV;

INSERT INTO Stage.ICU_INPUT_EVENTS_MV (
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, START_TIME, END_TIME, 
    ITEM_ID, AMOUNT, AMOUNT_UOM, RATE, RATE_UOM, CG_ID, PATIENT_WEIGHT, 
    TOTAL_AMOUNT, TOTAL_AMOUNT_UOM
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, START_TIME, END_TIME, 
    ITEM_ID, AMOUNT, AMOUNT_UOM, RATE, RATE_UOM, CG_ID, PATIENT_WEIGHT, 
    TOTAL_AMOUNT, TOTAL_AMOUNT_UOM
FROM Hospital.ICU.INPUT_EVENTS_MV
WHERE START_TIME > @LastInputStartTime;

-- INCREMENTAL LOAD: Clinic CALLOUT (Filtering by CREATE_TIME)
DECLARE @LastCalloutTime DATETIME;
SELECT @LastCalloutTime = ISNULL(MAX(CREATE_TIME), '2001-01-01') FROM Stage.Clinic_CALLOUT;

INSERT INTO Stage.Clinic_CALLOUT (
    ROW_ID, SUBJECT_ID, HADM_ID, SUBMIT_WARD_ID, SUBMIT_CARE_UNIT, 
    CURR_WARD_ID, CURR_CARE_UNIT, CALLOUT_WARD_ID, CALLOUT_SERVICE, 
    CALLOUT_STATUS, CALLOUT_OUTCOME, DISCHARGE_WARD_ID, ACKNOWLEDGE_STATUS, 
    CREATE_TIME, UPDATE_TIME, ACKNOWLEDGE_TIME, OUTCOME_TIME, 
    FIRST_RESERVATION_TIME, CURRENT_RESERVATION_TIME
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, SUBMIT_WARD_ID, SUBMIT_CARE_UNIT, 
    CURR_WARD_ID, CURR_CARE_UNIT, CALLOUT_WARD_ID, CALLOUT_SERVICE, 
    CALLOUT_STATUS, CALLOUT_OUTCOME, DISCHARGE_WARD_ID, ACKNOWLEDGE_STATUS, 
    CREATE_TIME, UPDATE_TIME, ACKNOWLEDGE_TIME, OUTCOME_TIME, 
    FIRST_RESERVATION_TIME, CURRENT_RESERVATION_TIME
FROM Hospital.Clinic.CALLOUT
WHERE CREATE_TIME > @LastCalloutTime;


-- INCREMENTAL LOAD: Clinic CPT_EVENTS (Filtering by CHART_DATE)
DECLARE @LastCptDate DATETIME;
SELECT @LastCptDate = ISNULL(MAX(CHART_DATE), '2001-01-01') FROM Stage.Clinic_CPT_EVENTS;

INSERT INTO Stage.Clinic_CPT_EVENTS (
    ROW_ID, SUBJECT_ID, HADM_ID, COST_CENTER, CHART_DATE, CPT_CD
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, COST_CENTER, CHART_DATE, CPT_CD
FROM Hospital.Clinic.CPT_EVENTS
WHERE CHART_DATE > @LastCptDate;


-- INCREMENTAL LOAD: Clinic PROCEDURES_ICD (Filtering by ROW_ID)
DECLARE @MaxProcRowID INT;
SELECT @MaxProcRowID = ISNULL(MAX(ROW_ID), 0) FROM Stage.Clinic_PROCEDURES_ICD;

INSERT INTO Stage.Clinic_PROCEDURES_ICD (
    ROW_ID, SUBJECT_ID, HADM_ID, SEQ_NUM, ICD9_CODE
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, SEQ_NUM, ICD9_CODE
FROM Hospital.Clinic.PROCEDURES_ICD
WHERE ROW_ID > @MaxProcRowID;

-- INCREMENTAL LOAD: Clinic TRANSFERS (Filtering by ROW_ID)
DECLARE @MaxTransferRowID INT;
SELECT @MaxTransferRowID = ISNULL(MAX(ROW_ID), 0) FROM Stage.Clinic_TRANSFERS;

INSERT INTO Stage.Clinic_TRANSFERS (
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, DB_SOURCE, EVENT_TYPE, 
    PREV_CAREUNIT, CURR_CAREUNIT, PREV_WARD_ID, CURR_WARD_ID, 
    IN_TIME, OUT_TIME, LOS
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, DB_SOURCE, EVENT_TYPE, 
    PREV_CAREUNIT, CURR_CAREUNIT, PREV_WARD_ID, CURR_WARD_ID, 
    IN_TIME, OUT_TIME, LOS
FROM Hospital.Clinic.TRANSFERS
WHERE ROW_ID > @MaxTransferRowID;

-- INCREMENTAL LOAD: ICU INPUT_EVENTS_CV (Filtering by CHART_TIME)
DECLARE @LastInputCVTime DATETIME;
SELECT @LastInputCVTime = ISNULL(MAX(CHART_TIME), '2001-01-01') FROM Stage.ICU_INPUT_EVENTS_CV;

INSERT INTO Stage.ICU_INPUT_EVENTS_CV (
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, CHART_TIME, ITEM_ID, 
    AMOUNT, AMOUNT_UOM, RATE, RATE_UOM, CG_ID
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, CHART_TIME, ITEM_ID, 
    AMOUNT, AMOUNT_UOM, RATE, RATE_UOM, CG_ID
FROM Hospital.ICU.INPUT_EVENTS_CV
WHERE CHART_TIME > @LastInputCVTime;


-- INCREMENTAL LOAD: ICU OUTPUT_EVENTS (Filtering by CHART_TIME)
DECLARE @LastOutputTime DATETIME;
SELECT @LastOutputTime = ISNULL(MAX(CHART_TIME), '2001-01-01') FROM Stage.ICU_OUTPUT_EVENTS;

INSERT INTO Stage.ICU_OUTPUT_EVENTS (
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, CHART_TIME, ITEM_ID, 
    [VALUE], VALUE_UOM, CG_ID
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, CHART_TIME, ITEM_ID, 
    [VALUE], VALUE_UOM, CG_ID
FROM Hospital.ICU.OUTPUT_EVENTS
WHERE CHART_TIME > @LastOutputTime;

-- INCREMENTAL LOAD: ICU PROCEDURE_EVENTS_MV (Filtering by START_TIME)
DECLARE @LastProcMVTime DATETIME;
SELECT @LastProcMVTime = ISNULL(MAX(START_TIME), '2001-01-01') FROM Stage.ICU_PROCEDURE_EVENTS_MV;

INSERT INTO Stage.ICU_PROCEDURE_EVENTS_MV (
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, START_TIME, END_TIME, 
    ITEM_ID, [VALUE], VALUE_UOM, [LOCATION], LOCATION_CATEGORY, CG_ID
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, START_TIME, END_TIME, 
    ITEM_ID, [VALUE], VALUE_UOM, [LOCATION], LOCATION_CATEGORY, CG_ID
FROM Hospital.ICU.PROCEDURE_EVENTS_MV
WHERE START_TIME > @LastProcMVTime;

-- INCREMENTAL LOAD: LAB_EVENTS (Filtering by CHART_TIME)
DECLARE @LastLabTime DATETIME;
SELECT @LastLabTime = ISNULL(MAX(CHART_TIME), '2001-01-01') FROM Stage.LAB_EVENTS;

INSERT INTO Stage.LAB_EVENTS (
    ROW_ID, PATIENT_ID, ADMISSION_ID, ITEM_ID, CHART_TIME, 
    [VALUE], VALUE_NUM, VALUE_UOM, FLAG, Extract_DateTime
)
SELECT 
    ROW_ID, PATIENT_ID, ADMISSION_ID, ITEM_ID, CHART_TIME, 
    [VALUE], VALUE_NUM, VALUE_UOM, FLAG, GETDATE()
FROM Laboratory.dbo.LAB_EVENTS
WHERE CHART_TIME > @LastLabTime;

-- Full Load Patients
TRUNCATE TABLE Stage.Clinic_PATIENTS;
INSERT INTO Stage.Clinic_PATIENTS (
    ROW_ID, SUBJECT_ID, GENDER, DOB, DOD, EXPIRE_FLAG
)
SELECT 
    ROW_ID, SUBJECT_ID, GENDER, DOB, DOD, EXPIRE_FLAG
FROM Hospital.Clinic.PATIENTS;

-- Full Load ICD-9 Diagnoses Dictionary
TRUNCATE TABLE Stage.Clinic_D_ICD_DIAGNOSES;
INSERT INTO Stage.Clinic_D_ICD_DIAGNOSES (
    ROW_ID, ICD9_CODE, SHORT_TITLE, LONG_TITLE
)
SELECT 
    ROW_ID, ICD9_CODE, SHORT_TITLE, LONG_TITLE
FROM Hospital.Clinic.D_ICD_DIAGNOSES;

-- Full Load ICD-9 Procedures Dictionary
TRUNCATE TABLE Stage.Clinic_D_ICD_PROCEDURES;
INSERT INTO Stage.Clinic_D_ICD_PROCEDURES (
    ROW_ID, ICD9_CODE, SHORT_TITLE, LONG_TITLE
)
SELECT 
    ROW_ID, ICD9_CODE, SHORT_TITLE, LONG_TITLE
FROM Hospital.Clinic.D_ICD_PROCEDURES;

-- Full Load CPT Code Catalog
TRUNCATE TABLE Stage.Clinic_D_CPT;
INSERT INTO Stage.Clinic_D_CPT (
    ROW_ID, CATEGORY, SECTION_RANGE, SECTION_HEADER, SUBSECTION_RANGE, 
    SUBSECTION_HEADER, CODE_SUFFIX, MIN_CODE_IN_SUBSECTION, MAX_CODE_IN_SUBSECTION
)
SELECT 
    ROW_ID, CATEGORY, SECTION_RANGE, SECTION_HEADER, SUBSECTION_RANGE, 
    SUBSECTION_HEADER, CODE_SUFFIX, MIN_CODE_IN_SUBSECTION, MAX_CODE_IN_SUBSECTION
FROM Hospital.Clinic.D_CPT;

-- Full Load Services
TRUNCATE TABLE Stage.Clinic_SERVICES;
INSERT INTO Stage.Clinic_SERVICES (
    ROW_ID, SUBJECT_ID, HADM_ID, TRANSFER_TIME, PREV_SERVICE, CURR_SERVICE
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, TRANSFER_TIME, PREV_SERVICE, CURR_SERVICE
FROM Hospital.Clinic.SERVICES;

-- Full Load ICU Items Dictionary
TRUNCATE TABLE Stage.ICU_D_ITEMS;
INSERT INTO Stage.ICU_D_ITEMS (
    ROW_ID, ITEM_ID, LABEL, ABBREVIATION, DB_SOURCE, 
    CATEGORY, UNIT_NAME, PARAM_TYPE 
)
SELECT 
    ROW_ID, ITEM_ID, LABEL, ABBREVIATION, DB_SOURCE, 
    CATEGORY, UNIT_NAME, PARAM_TYPE
FROM Hospital.ICU.D_ITEMS;

-- Full Load Caregivers
TRUNCATE TABLE Stage.ICU_CAREGIVERS;
INSERT INTO Stage.ICU_CAREGIVERS (
    ROW_ID, CG_ID, LABEL, [DESCRIPTION]
)
SELECT 
    ROW_ID, CG_ID, LABEL, [DESCRIPTION]
FROM Hospital.ICU.CAREGIVERS;

-- Full Load: DRG Codes
TRUNCATE TABLE Stage.Clinic_DRG_CODES;
INSERT INTO Stage.Clinic_DRG_CODES (
    ROW_ID, SUBJECT_ID, HADM_ID, DRG_TYPE, DRG_CODE
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, DRG_TYPE, DRG_CODE
FROM Hospital.Clinic.DRG_CODES;

-- Full Load: ICU Stays
TRUNCATE TABLE Stage.ICU_STAYS;
INSERT INTO Stage.ICU_STAYS (
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, DB_SOURCE, 
    FIRST_CARE_UNIT, LAST_CARE_UNIT, FIRST_WARD_ID, LAST_WARD_ID, 
    IN_TIME, OUT_TIME, LOS
)
SELECT 
    ROW_ID, SUBJECT_ID, HADM_ID, ICU_STAY_ID, DB_SOURCE, 
    FIRST_CARE_UNIT, LAST_CARE_UNIT, FIRST_WARD_ID, LAST_WARD_ID, 
    IN_TIME, OUT_TIME, LOS
FROM Hospital.ICU.ICU_STAYS;

-- Full Load: Lab Items
TRUNCATE TABLE Stage.D_LAB_ITEMS;
INSERT INTO Stage.D_LAB_ITEMS (
    ROW_ID, ITEM_ID, LABEL, FLUID, CATEGORY, LOINC_CODE
)
SELECT 
    ROW_ID, ITEM_ID, LABEL, FLUID, CATEGORY, ISNULL(LOINC_CODE, 'Unknown') AS LOINC_CODE
FROM Laboratory.dbo.D_LAB_ITEMS;
