--- CREATE DATABASE ---
CREATE DATABASE Laboratory;
GO
USE Laboratory;

--- CREATE SCHEMA ---
CREATE SCHEMA Lab;
GO

--- CREATE TABLES ---
CREATE TABLE Lab.D_LAB_ITEMS (
  	ROW_ID INT NOT NULL,
	ITEM_ID INT NOT NULL,
	LABEL VARCHAR(100) NOT NULL,
	FLUID VARCHAR(100) NOT NULL,
	CATEGORY VARCHAR(100) NOT NULL,
	LOINC_CODE VARCHAR(100),
	CONSTRAINT dlabitems_itemid_unique UNIQUE (ITEM_ID),
	CONSTRAINT dlabitems_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Lab.LAB_EVENTS (
  	ROW_ID INT NOT NULL,
	PATIENT_ID INT NOT NULL,
	ADMISSION_ID INT,
	ITEM_ID INT NOT NULL,
	CHART_TIME DATETIME,
	[VALUE] VARCHAR(200),
	VALUE_NUM DOUBLE PRECISION,
	VALUE_UOM VARCHAR(20),
	FLAG VARCHAR(20),
	CONSTRAINT labevents_rowid_pk PRIMARY KEY (ROW_ID)
);
GO
ALTER TABLE Lab.LAB_EVENTS DROP CONSTRAINT IF EXISTS labevents_fk_itemid;
ALTER TABLE Lab.LAB_EVENTS
ADD CONSTRAINT labevents_fk_itemid
    FOREIGN KEY (ITEM_ID)
    REFERENCES Lab.D_LAB_ITEMS(ITEM_ID);
GO

--- CREATE INDEX ---
CREATE INDEX D_LABITEMS_idx01
    ON Lab.D_LAB_ITEMS (ITEM_ID);

CREATE INDEX D_LABITEMS_idx02
    ON Lab.D_LAB_ITEMS (LABEL);

CREATE INDEX D_LABITEMS_idx03
    ON Lab.D_LAB_ITEMS (LOINC_CODE);

CREATE INDEX LABEVENTS_idx01
    ON Lab.LAB_EVENTS (PATIENT_ID);

CREATE INDEX LABEVENTS_idx02
    ON Lab.LAB_EVENTS (ADMISSION_ID);

CREATE INDEX LABEVENTS_idx03
    ON Lab.LAB_EVENTS (ITEM_ID);
