BULK INSERT Lab.D_LAB_ITEMS
FROM 'path\to\dir\D_LAB_ITEMS.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', KEEPNULLS);

BULK INSERT Lab.LAB_EVENTS
FROM 'path\to\dir\LAB_EVENTS.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', KEEPNULLS);
