--- ADMISSIONS --- 
ALTER TABLE Clinic.ADMISSIONS DROP CONSTRAINT IF EXISTS admissions_fk_subject_id;
ALTER TABLE Clinic.ADMISSIONS
ADD CONSTRAINT admissions_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

--- CALLOUT ---
ALTER TABLE Clinic.CALLOUT DROP CONSTRAINT IF EXISTS callout_fk_subject_id;
ALTER TABLE Clinic.CALLOUT
ADD CONSTRAINT callout_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.CALLOUT DROP CONSTRAINT IF EXISTS callout_fk_hadm_id;
ALTER TABLE Clinic.CALLOUT
ADD CONSTRAINT callout_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

--- DIAGNOSES_ICD ---
ALTER TABLE Clinic.DIAGNOSES_ICD DROP CONSTRAINT IF EXISTS diagnoses_icd_fk_subject_id;
ALTER TABLE Clinic.DIAGNOSES_ICD
ADD CONSTRAINT diagnoses_icd_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.DIAGNOSES_ICD DROP CONSTRAINT IF EXISTS diagnoses_icd_fk_hadm_id;
ALTER TABLE Clinic.DIAGNOSES_ICD
ADD CONSTRAINT diagnoses_icd_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE Clinic.DIAGNOSES_ICD DROP CONSTRAINT IF EXISTS diagnoses_icd_fk_icd9;
ALTER TABLE Clinic.DIAGNOSES_ICD
ADD CONSTRAINT diagnoses_icd_fk_icd9
    FOREIGN KEY (ICD9_CODE)
    REFERENCES Clinic.D_ICD_DIAGNOSES(ICD9_CODE);

--- ICU_STAYS ---
ALTER TABLE ICU.ICU_STAYS DROP CONSTRAINT IF EXISTS icustays_fk_subject_id;
ALTER TABLE ICU.ICU_STAYS
ADD CONSTRAINT icustays_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.ICU_STAYS DROP CONSTRAINT IF EXISTS icustays_fk_hadm_id;
ALTER TABLE ICU.ICU_STAYS
ADD CONSTRAINT icustays_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

--- INPUT_EVENTS_CV ---
ALTER TABLE ICU.INPUT_EVENTS_CV DROP CONSTRAINT IF EXISTS inputevents_cv_fk_subject_id;
ALTER TABLE ICU.INPUT_EVENTS_CV
ADD CONSTRAINT inputevents_cv_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.INPUT_EVENTS_CV DROP CONSTRAINT IF EXISTS inputevents_cv_fk_hadm_id;
ALTER TABLE ICU.INPUT_EVENTS_CV
ADD CONSTRAINT inputevents_cv_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE ICU.INPUT_EVENTS_CV DROP CONSTRAINT IF EXISTS inputevents_cv_fk_icustay_id;
ALTER TABLE ICU.INPUT_EVENTS_CV
ADD CONSTRAINT inputevents_cv_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);

ALTER TABLE ICU.INPUT_EVENTS_CV DROP CONSTRAINT IF EXISTS inputevents_cv_fk_cgid;
ALTER TABLE ICU.INPUT_EVENTS_CV
ADD CONSTRAINT inputevents_cv_fk_cgid
    FOREIGN KEY (CG_ID)
    REFERENCES ICU.CAREGIVERS(CG_ID);

--- INPUT_EVENTS_MV ---
ALTER TABLE ICU.INPUT_EVENTS_MV DROP CONSTRAINT IF EXISTS inputevents_mv_fk_subject_id;
ALTER TABLE ICU.INPUT_EVENTS_MV
ADD CONSTRAINT inputevents_mv_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.INPUT_EVENTS_MV DROP CONSTRAINT IF EXISTS inputevents_mv_fk_hadm_id;
ALTER TABLE ICU.INPUT_EVENTS_MV
ADD CONSTRAINT inputevents_mv_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE ICU.INPUT_EVENTS_MV DROP CONSTRAINT IF EXISTS inputevents_mv_fk_icustay_id;
ALTER TABLE ICU.INPUT_EVENTS_MV
ADD CONSTRAINT inputevents_mv_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);

ALTER TABLE ICU.INPUT_EVENTS_MV DROP CONSTRAINT IF EXISTS inputevents_mv_fk_itemid;
ALTER TABLE ICU.INPUT_EVENTS_MV
ADD CONSTRAINT inputevents_mv_fk_itemid
    FOREIGN KEY (ITEM_ID)
    REFERENCES ICU.D_ITEMS(ITEM_ID);

ALTER TABLE ICU.INPUT_EVENTS_MV DROP CONSTRAINT IF EXISTS inputevents_mv_fk_cgid;
ALTER TABLE ICU.INPUT_EVENTS_MV
ADD CONSTRAINT inputevents_mv_fk_cgid
    FOREIGN KEY (CG_ID)
    REFERENCES ICU.CAREGIVERS(CG_ID);

--- OUTPUT_EVENTS ---
ALTER TABLE ICU.OUTPUT_EVENTS DROP CONSTRAINT IF EXISTS outputevents_subject_id;
ALTER TABLE ICU.OUTPUT_EVENTS
ADD CONSTRAINT outputevents_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.OUTPUT_EVENTS DROP CONSTRAINT IF EXISTS outputevents_hadm_id;
ALTER TABLE ICU.OUTPUT_EVENTS
ADD CONSTRAINT outputevents_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE ICU.OUTPUT_EVENTS DROP CONSTRAINT IF EXISTS outputevents_icustay_id;
ALTER TABLE ICU.OUTPUT_EVENTS
ADD CONSTRAINT outputevents_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);

ALTER TABLE ICU.OUTPUT_EVENTS DROP CONSTRAINT IF EXISTS outputevents_fk_itemid;
ALTER TABLE ICU.OUTPUT_EVENTS
ADD CONSTRAINT outputevents_fk_itemid
    FOREIGN KEY (ITEM_ID)
    REFERENCES ICU.D_ITEMS(ITEM_ID);

ALTER TABLE ICU.OUTPUT_EVENTS DROP CONSTRAINT IF EXISTS outputevents_cgid;
ALTER TABLE ICU.OUTPUT_EVENTS
ADD CONSTRAINT outputevents_fk_cgid
    FOREIGN KEY (CG_ID)
    REFERENCES ICU.CAREGIVERS(CG_ID);

--- PROCEDURE_EVENTS_MV ---
ALTER TABLE ICU.PROCEDURE_EVENTS_MV DROP CONSTRAINT IF EXISTS procedureevents_mv_fk_subject_id;
ALTER TABLE ICU.PROCEDURE_EVENTS_MV
ADD CONSTRAINT procedureevents_mv_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.PROCEDURE_EVENTS_MV DROP CONSTRAINT IF EXISTS procedureevents_mv_fk_hadm_id;
ALTER TABLE ICU.PROCEDURE_EVENTS_MV
ADD CONSTRAINT procedureevents_mv_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE ICU.PROCEDURE_EVENTS_MV DROP CONSTRAINT IF EXISTS procedureevents_mv_fk_icustay_id;
ALTER TABLE ICU.PROCEDURE_EVENTS_MV
ADD CONSTRAINT procedureevents_mv_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);

ALTER TABLE ICU.PROCEDURE_EVENTS_MV DROP CONSTRAINT IF EXISTS procedureevents_mv_fk_itemid;
ALTER TABLE ICU.PROCEDURE_EVENTS_MV
ADD CONSTRAINT procedureevents_mv_fk_itemid
    FOREIGN KEY (ITEM_ID)
    REFERENCES ICU.D_ITEMS(ITEM_ID);

ALTER TABLE ICU.PROCEDURE_EVENTS_MV DROP CONSTRAINT IF EXISTS procedureevents_mv_fk_cgid;
ALTER TABLE ICU.PROCEDURE_EVENTS_MV
ADD CONSTRAINT procedureevents_mv_fk_cgid
    FOREIGN KEY (CG_ID)
    REFERENCES ICU.CAREGIVERS(CG_ID);

--- SERVICES ---
ALTER TABLE Clinic.[SERVICES] DROP CONSTRAINT IF EXISTS services_fk_subject_id;
ALTER TABLE Clinic.[SERVICES]
ADD CONSTRAINT services_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.[SERVICES] DROP CONSTRAINT IF EXISTS services_fk_hadm_id;
ALTER TABLE Clinic.[SERVICES]
ADD CONSTRAINT services_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

--- TRANSFERS ---
ALTER TABLE Clinic.TRANSFERS DROP CONSTRAINT IF EXISTS transfers_fk_subject_id;
ALTER TABLE Clinic.TRANSFERS
ADD CONSTRAINT transfers_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.TRANSFERS DROP CONSTRAINT IF EXISTS transfers_fk_hadm_id;
ALTER TABLE Clinic.TRANSFERS
ADD CONSTRAINT transfers_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE Clinic.TRANSFERS DROP CONSTRAINT IF EXISTS transfers_fk_icustay_id;
ALTER TABLE Clinic.TRANSFERS
ADD CONSTRAINT transfers_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);
