--- ADMISSIONS --- 
ALTER TABLE Clinic.ADMISSIONS DROP CONSTRAINT IF EXISTS admissions_fk_subject_id;
ALTER TABLE Clinic.ADMISSIONS
ADD CONSTRAINT admissions_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

--- CALLOUT ---
ALTER TABLE Clinic.CALLOUT DROP CONSTRAINT IF EXISTS callout_fk_subject_id;
ALTER TABLE Clinic.CALLOUT
ADD CONSTRAINT callout_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.CALLOUT DROP CONSTRAINT IF EXISTS callout_fk_hadm_id;
ALTER TABLE Clinic.CALLOUT
ADD CONSTRAINT callout_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

--- CPT_EVENTS ---
ALTER TABLE Clinic.CPT_EVENTS DROP CONSTRAINT IF EXISTS cptevents_fk_subject_id;
ALTER TABLE Clinic.CPT_EVENTS
ADD CONSTRAINT cptevents_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.CPT_EVENTS DROP CONSTRAINT IF EXISTS cptevents_fk_hadm_id;
ALTER TABLE Clinic.CPT_EVENTS
ADD CONSTRAINT cptevents_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

--- DATETIME_EVENTS ---
ALTER TABLE ICU.DATETIME_EVENTS DROP CONSTRAINT IF EXISTS datetimeevents_fk_subject_id;
ALTER TABLE ICU.DATETIME_EVENTS
ADD CONSTRAINT datetimeevents_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.DATETIME_EVENTS DROP CONSTRAINT IF EXISTS datetimeevents_fk_cgid;
ALTER TABLE ICU.DATETIME_EVENTS
ADD CONSTRAINT datetimeevents_fk_cgid
    FOREIGN KEY (CG_ID)
    REFERENCES ICU.CAREGIVERS(CG_ID);

ALTER TABLE ICU.DATETIME_EVENTS DROP CONSTRAINT IF EXISTS datetimeevents_fk_hadm_id;
ALTER TABLE ICU.DATETIME_EVENTS
ADD CONSTRAINT datetimeevents_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE ICU.DATETIME_EVENTS DROP CONSTRAINT IF EXISTS datetimeevents_fk_itemid;
ALTER TABLE ICU.DATETIME_EVENTS
ADD CONSTRAINT datetimeevents_fk_itemid
    FOREIGN KEY (ITEM_ID)
    REFERENCES ICU.D_ITEMS(ITEM_ID);

ALTER TABLE ICU.DATETIME_EVENTS DROP CONSTRAINT IF EXISTS datetimeevents_fk_icustay_id;
ALTER TABLE ICU.DATETIME_EVENTS
ADD CONSTRAINT datetimeevents_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);

--- DIAGNOSES_ICD ---
ALTER TABLE Clinic.DIAGNOSES_ICD DROP CONSTRAINT IF EXISTS diagnoses_icd_fk_subject_id;
ALTER TABLE Clinic.DIAGNOSES_ICD
ADD CONSTRAINT diagnoses_icd_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.DIAGNOSES_ICD DROP CONSTRAINT IF EXISTS diagnoses_icd_fk_hadm_id;
ALTER TABLE Clinic.DIAGNOSES_ICD
ADD CONSTRAINT diagnoses_icd_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE Clinic.DIAGNOSES_ICD DROP CONSTRAINT IF EXISTS diagnoses_icd_fk_icd9;
ALTER TABLE Clinic.DIAGNOSES_ICD
ADD CONSTRAINT diagnoses_icd_fk_icd9
    FOREIGN KEY (ICD9_CODE)
    REFERENCES Clinic.D_ICD_DIAGNOSES(ICD9_CODE);

--- DRG_CODES ---
ALTER TABLE Clinic.DRG_CODES DROP CONSTRAINT IF EXISTS drgcodes_fk_subject_id;
ALTER TABLE Clinic.DRG_CODES
ADD CONSTRAINT drgcodes_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.DRG_CODES DROP CONSTRAINT IF EXISTS drgcodes_fk_hadm_id;
ALTER TABLE Clinic.DRG_CODES
ADD CONSTRAINT drgcodes_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

--- ICU_STAYS ---
ALTER TABLE ICU.ICU_STAYS DROP CONSTRAINT IF EXISTS icustays_fk_subject_id;
ALTER TABLE ICU.ICU_STAYS
ADD CONSTRAINT icustays_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.ICU_STAYS DROP CONSTRAINT IF EXISTS icustays_fk_hadm_id;
ALTER TABLE ICU.ICU_STAYS
ADD CONSTRAINT icustays_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

--- INPUT_EVENTS_CV ---
ALTER TABLE ICU.INPUT_EVENTS_CV DROP CONSTRAINT IF EXISTS inputevents_cv_fk_subject_id;
ALTER TABLE ICU.INPUT_EVENTS_CV
ADD CONSTRAINT inputevents_cv_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.INPUT_EVENTS_CV DROP CONSTRAINT IF EXISTS inputevents_cv_fk_hadm_id;
ALTER TABLE ICU.INPUT_EVENTS_CV
ADD CONSTRAINT inputevents_cv_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE ICU.INPUT_EVENTS_CV DROP CONSTRAINT IF EXISTS inputevents_cv_fk_icustay_id;
ALTER TABLE ICU.INPUT_EVENTS_CV
ADD CONSTRAINT inputevents_cv_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);

ALTER TABLE ICU.INPUT_EVENTS_CV DROP CONSTRAINT IF EXISTS inputevents_cv_fk_cgid;
ALTER TABLE ICU.INPUT_EVENTS_CV
ADD CONSTRAINT inputevents_cv_fk_cgid
    FOREIGN KEY (CG_ID)
    REFERENCES ICU.CAREGIVERS(CG_ID);

--- INPUT_EVENTS_MV ---
ALTER TABLE ICU.INPUT_EVENTS_MV DROP CONSTRAINT IF EXISTS inputevents_mv_fk_subject_id;
ALTER TABLE ICU.INPUT_EVENTS_MV
ADD CONSTRAINT inputevents_mv_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.INPUT_EVENTS_MV DROP CONSTRAINT IF EXISTS inputevents_mv_fk_hadm_id;
ALTER TABLE ICU.INPUT_EVENTS_MV
ADD CONSTRAINT inputevents_mv_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE ICU.INPUT_EVENTS_MV DROP CONSTRAINT IF EXISTS inputevents_mv_fk_icustay_id;
ALTER TABLE ICU.INPUT_EVENTS_MV
ADD CONSTRAINT inputevents_mv_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);

ALTER TABLE ICU.INPUT_EVENTS_MV DROP CONSTRAINT IF EXISTS inputevents_mv_fk_itemid;
ALTER TABLE ICU.INPUT_EVENTS_MV
ADD CONSTRAINT inputevents_mv_fk_itemid
    FOREIGN KEY (ITEM_ID)
    REFERENCES ICU.D_ITEMS(ITEM_ID);

ALTER TABLE ICU.INPUT_EVENTS_MV DROP CONSTRAINT IF EXISTS inputevents_mv_fk_cgid;
ALTER TABLE ICU.INPUT_EVENTS_MV
ADD CONSTRAINT inputevents_mv_fk_cgid
    FOREIGN KEY (CG_ID)
    REFERENCES ICU.CAREGIVERS(CG_ID);

-- MICROBIOLOGY_EVENTS ---
ALTER TABLE Clinic.MICROBIOLOGY_EVENTS DROP CONSTRAINT IF EXISTS microbiologyevents_fk_subject_id;
ALTER TABLE Clinic.MICROBIOLOGY_EVENTS
ADD CONSTRAINT microbiologyevents_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.MICROBIOLOGY_EVENTS DROP CONSTRAINT IF EXISTS microbiologyevents_fk_hadm_id;
ALTER TABLE Clinic.MICROBIOLOGY_EVENTS
ADD CONSTRAINT microbiologyevents_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE Clinic.MICROBIOLOGY_EVENTS DROP CONSTRAINT IF EXISTS microbiologyevents_fk_spec_itemid;
ALTER TABLE Clinic.MICROBIOLOGY_EVENTS
ADD CONSTRAINT microbiologyevents_fk_spec_itemid
    FOREIGN KEY (SPEC_ITEM_ID)
    REFERENCES ICU.D_ITEMS(ITEM_ID);

ALTER TABLE Clinic.MICROBIOLOGY_EVENTS DROP CONSTRAINT IF EXISTS microbiologyevents_fk_org_itemid;
ALTER TABLE Clinic.MICROBIOLOGY_EVENTS
ADD CONSTRAINT microbiologyevents_fk_org_itemid
    FOREIGN KEY (ORG_ITEM_ID)
    REFERENCES ICU.D_ITEMS(ITEM_ID);

ALTER TABLE Clinic.MICROBIOLOGY_EVENTS DROP CONSTRAINT IF EXISTS microbiologyevents_fk_ab_itemid;
ALTER TABLE Clinic.MICROBIOLOGY_EVENTS
ADD CONSTRAINT microbiologyevents_fk_ab_itemid
    FOREIGN KEY (AB_ITEM_ID)
    REFERENCES ICU.D_ITEMS(ITEM_ID);

--- OUTPUT_EVENTS ---
ALTER TABLE ICU.OUTPUT_EVENTS DROP CONSTRAINT IF EXISTS outputevents_subject_id;
ALTER TABLE ICU.OUTPUT_EVENTS
ADD CONSTRAINT outputevents_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.OUTPUT_EVENTS DROP CONSTRAINT IF EXISTS outputevents_hadm_id;
ALTER TABLE ICU.OUTPUT_EVENTS
ADD CONSTRAINT outputevents_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE ICU.OUTPUT_EVENTS DROP CONSTRAINT IF EXISTS outputevents_icustay_id;
ALTER TABLE ICU.OUTPUT_EVENTS
ADD CONSTRAINT outputevents_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);

ALTER TABLE ICU.OUTPUT_EVENTS DROP CONSTRAINT IF EXISTS outputevents_fk_itemid;
ALTER TABLE ICU.OUTPUT_EVENTS
ADD CONSTRAINT outputevents_fk_itemid
    FOREIGN KEY (ITEM_ID)
    REFERENCES ICU.D_ITEMS(ITEM_ID);

ALTER TABLE ICU.OUTPUT_EVENTS DROP CONSTRAINT IF EXISTS outputevents_cgid;
ALTER TABLE ICU.OUTPUT_EVENTS
ADD CONSTRAINT outputevents_fk_cgid
    FOREIGN KEY (CG_ID)
    REFERENCES ICU.CAREGIVERS(CG_ID);

--- PRESCRIPTIONS ---
ALTER TABLE Clinic.PRESCRIPTIONS DROP CONSTRAINT IF EXISTS prescriptions_fk_subject_id;
ALTER TABLE Clinic.PRESCRIPTIONS
ADD CONSTRAINT prescriptions_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.PRESCRIPTIONS DROP CONSTRAINT IF EXISTS prescriptions_fk_hadm_id;
ALTER TABLE Clinic.PRESCRIPTIONS
ADD CONSTRAINT prescriptions_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE Clinic.PRESCRIPTIONS DROP CONSTRAINT IF EXISTS prescriptions_fk_icustay_id;
ALTER TABLE Clinic.PRESCRIPTIONS
ADD CONSTRAINT prescriptions_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);

--- PROCEDURE_EVENTS_MV ---
ALTER TABLE ICU.PROCEDURE_EVENTS_MV DROP CONSTRAINT IF EXISTS procedureevents_mv_fk_subject_id;
ALTER TABLE ICU.PROCEDURE_EVENTS_MV
ADD CONSTRAINT procedureevents_mv_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE ICU.PROCEDURE_EVENTS_MV DROP CONSTRAINT IF EXISTS procedureevents_mv_fk_hadm_id;
ALTER TABLE ICU.PROCEDURE_EVENTS_MV
ADD CONSTRAINT procedureevents_mv_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE ICU.PROCEDURE_EVENTS_MV DROP CONSTRAINT IF EXISTS procedureevents_mv_fk_icustay_id;
ALTER TABLE ICU.PROCEDURE_EVENTS_MV
ADD CONSTRAINT procedureevents_mv_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);

ALTER TABLE ICU.PROCEDURE_EVENTS_MV DROP CONSTRAINT IF EXISTS procedureevents_mv_fk_itemid;
ALTER TABLE ICU.PROCEDURE_EVENTS_MV
ADD CONSTRAINT procedureevents_mv_fk_itemid
    FOREIGN KEY (ITEM_ID)
    REFERENCES ICU.D_ITEMS(ITEM_ID);

ALTER TABLE ICU.PROCEDURE_EVENTS_MV DROP CONSTRAINT IF EXISTS procedureevents_mv_fk_cgid;
ALTER TABLE ICU.PROCEDURE_EVENTS_MV
ADD CONSTRAINT procedureevents_mv_fk_cgid
    FOREIGN KEY (CG_ID)
    REFERENCES ICU.CAREGIVERS(CG_ID);

--- PROCEDURES_ICD ---
ALTER TABLE Clinic.PROCEDURES_ICD DROP CONSTRAINT IF EXISTS procedures_icd_fk_subject_id;
ALTER TABLE Clinic.PROCEDURES_ICD
ADD CONSTRAINT procedures_icd_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.PROCEDURES_ICD DROP CONSTRAINT IF EXISTS procedures_icd_fk_hadm_id;
ALTER TABLE Clinic.PROCEDURES_ICD
ADD CONSTRAINT procedures_icd_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE Clinic.PROCEDURES_ICD DROP CONSTRAINT IF EXISTS procedures_icd_fk_icd9;
ALTER TABLE Clinic.PROCEDURES_ICD
ADD CONSTRAINT procedures_icd_fk_icd9
    FOREIGN KEY (ICD9_CODE)
    REFERENCES Clinic.D_ICD_PROCEDURES(ICD9_CODE);

--- SERVICES ---
ALTER TABLE Clinic.[SERVICES] DROP CONSTRAINT IF EXISTS services_fk_subject_id;
ALTER TABLE Clinic.[SERVICES]
ADD CONSTRAINT services_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.[SERVICES] DROP CONSTRAINT IF EXISTS services_fk_hadm_id;
ALTER TABLE Clinic.[SERVICES]
ADD CONSTRAINT services_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

--- TRANSFERS ---
ALTER TABLE Clinic.TRANSFERS DROP CONSTRAINT IF EXISTS transfers_fk_subject_id;
ALTER TABLE Clinic.TRANSFERS
ADD CONSTRAINT transfers_fk_subject_id
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES Clinic.PATIENTS(SUBJECT_ID);

ALTER TABLE Clinic.TRANSFERS DROP CONSTRAINT IF EXISTS transfers_fk_hadm_id;
ALTER TABLE Clinic.TRANSFERS
ADD CONSTRAINT transfers_fk_hadm_id
    FOREIGN KEY (HADM_ID)
    REFERENCES Clinic.ADMISSIONS(HADM_ID);

ALTER TABLE Clinic.TRANSFERS DROP CONSTRAINT IF EXISTS transfers_fk_icustay_id;
ALTER TABLE Clinic.TRANSFERS
ADD CONSTRAINT transfers_fk_icustay_id
    FOREIGN KEY (ICU_STAY_ID)
    REFERENCES ICU.ICU_STAYS(ICU_STAY_ID);
