--- CREATE SCHEMAS ---
CREATE SCHEMA Clinic;
GO
CREATE SCHEMA ICU;
GO

--- CREATE TABLES ---
CREATE TABLE Clinic.ADMISSIONS (
	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	ADMIT_TIME DATETIME NOT NULL,
	DISCH_TIME DATETIME NOT NULL,
	DEATH_TIME DATETIME,
	ADMISSION_TYPE VARCHAR(50) NOT NULL,
	ADMISSION_LOCATION VARCHAR(50) NOT NULL,
	DISCHARGE_LOCATION VARCHAR(50) NOT NULL,
	INSURANCE VARCHAR(255) NOT NULL,
	[LANGUAGE] VARCHAR(10),
	RELIGION VARCHAR(50),
	MARITAL_STATUS VARCHAR(50),
	ETHNICITY VARCHAR(200) NOT NULL,
	ED_REG_TIME DATETIME,
	ED_OUT_TIME DATETIME,
	DIAGNOSIS VARCHAR(255),
	HOSPITAL_EXPIRE_FLAG SMALLINT,
	HAS_CHARTEVENTS_DATA SMALLINT NOT NULL,
	CONSTRAINT adm_rowid_pk PRIMARY KEY (ROW_ID),
	CONSTRAINT adm_hadm_unique UNIQUE (HADM_ID)
);

CREATE TABLE Clinic.CALLOUT (
	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	SUBMIT_WARD_ID INT,
	SUBMIT_CARE_UNIT VARCHAR(15),
	CURR_WARD_ID INT,
	CURR_CARE_UNIT VARCHAR(15),
	CALLOUT_WARD_ID INT,
	CALLOUT_SERVICE VARCHAR(10) NOT NULL,
	REQUEST_TELE SMALLINT NOT NULL,
	REQUEST_RESP SMALLINT NOT NULL,
	REQUEST_CDIFF SMALLINT NOT NULL,
	REQUEST_MRSA SMALLINT NOT NULL,
	REQUEST_VRE SMALLINT NOT NULL,
	CALLOUT_STATUS VARCHAR(20) NOT NULL,
	CALLOUT_OUTCOME VARCHAR(20) NOT NULL,
	DISCHARGE_WARD_ID INT,
	ACKNOWLEDGE_STATUS VARCHAR(20) NOT NULL,
	CREATE_TIME DATETIME NOT NULL,
	UPDATE_TIME DATETIME NOT NULL,
	ACKNOWLEDGE_TIME DATETIME,
	OUTCOME_TIME DATETIME NOT NULL,
	FIRST_RESERVATION_TIME DATETIME,
	CURRENT_RESERVATION_TIME DATETIME,
	CONSTRAINT callout_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.CPT_EVENTS (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	COST_CENTER VARCHAR(10) NOT NULL,
	CHART_DATE DATETIME,
	CPT_CD VARCHAR(10) NOT NULL,
	CPT_NUMBER VARCHAR(20),
	CPT_SUFFIX VARCHAR(5),
	TICKET_ID_SEQ VARCHAR(20),
	SECTION_HEADER VARCHAR(50),
	SUBSECTION_HEADER VARCHAR(255),
	[DESCRIPTION] VARCHAR(200),
	CONSTRAINT cpt_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.DIAGNOSES_ICD (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	SEQ_NUM VARCHAR(20),
	ICD9_CODE VARCHAR(10),
	CONSTRAINT diagnosesicd_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.DRG_CODES (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	DRG_TYPE VARCHAR(20) NOT NULL,
	DRG_CODE VARCHAR(20) NOT NULL,
	[DESCRIPTION] VARCHAR(255),
	DRG_SEVERITY VARCHAR(20),
	DRG_MORTALITY VARCHAR(20),
	CONSTRAINT drg_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.D_CPT (
  	ROW_ID INT NOT NULL,
	CATEGORY SMALLINT NOT NULL,
	SECTION_RANGE VARCHAR(100) NOT NULL,
	SECTION_HEADER VARCHAR(50) NOT NULL,
	SUBSECTION_RANGE VARCHAR(100) NOT NULL,
	SUBSECTION_HEADER VARCHAR(255) NOT NULL,
	CODE_SUFFIX VARCHAR(5),
	MIN_CODE_IN_SUBSECTION INT NOT NULL,
	MAX_CODE_IN_SUBSECTION INT NOT NULL,
	CONSTRAINT dcpt_ssrange_unique UNIQUE (SUBSECTION_RANGE),
	CONSTRAINT dcpt_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.D_ICD_DIAGNOSES (
  	ROW_ID INT NOT NULL,
	ICD9_CODE VARCHAR(10) NOT NULL,
	SHORT_TITLE VARCHAR(50) NOT NULL,
	LONG_TITLE VARCHAR(255) NOT NULL,
	CONSTRAINT d_icd_diag_code_unique UNIQUE (ICD9_CODE),
	CONSTRAINT d_icd_diag_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.D_ICD_PROCEDURES (
  	ROW_ID INT NOT NULL,
	ICD9_CODE VARCHAR(10) NOT NULL,
	SHORT_TITLE VARCHAR(50) NOT NULL,
	LONG_TITLE VARCHAR(255) NOT NULL,
	CONSTRAINT d_icd_proc_code_unique UNIQUE (ICD9_CODE),
	CONSTRAINT d_icd_proc_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.MICROBIOLOGY_EVENTS (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT,
	CHART_DATE DATETIME,
	CHART_TIME DATETIME,
	SPEC_ITEM_ID INT,
	SPEC_TYPE_DESC VARCHAR(100),
	ORG_ITEM_ID INT,
	ORG_NAME VARCHAR(100),
	ISOLATE_NUM SMALLINT,
	AB_ITEM_ID INT,
	AB_NAME VARCHAR(30),
	DILUTION_TEXT VARCHAR(10),
	DILUTION_COMPARISON VARCHAR(20),
	DILUTION_VALUE DOUBLE PRECISION,
	INTERPRETATION VARCHAR(5),
	CONSTRAINT micro_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.PATIENTS (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	GENDER VARCHAR(5) NOT NULL,
	DOB DATETIME,
	DOD DATETIME,
	DOD_HOSP DATETIME,
	DOD_SSN DATETIME,
	EXPIRE_FLAG INT NOT NULL,
	CONSTRAINT pat_subid_unique UNIQUE (SUBJECT_ID),
	CONSTRAINT pat_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.PRESCRIPTIONS (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	ICU_STAY_ID INT,
	[START_DATE] DATETIME,
	END_DATE DATETIME,
	DRUG_TYPE VARCHAR(100) NOT NULL,
	DRUG VARCHAR(100) NOT NULL,
	DRUG_NAME_POE VARCHAR(100),
	DRUG_NAME_GENERIC VARCHAR(100),
	FORMULARY_DRUG_CD VARCHAR(120),
	GSN VARCHAR(200),
	NDC VARCHAR(120),
	PROD_STRENGTH VARCHAR(120),
	DOSE_VAL_RX VARCHAR(120),
	DOSE_UNIT_RX VARCHAR(120),
	FORM_VAL_DISP VARCHAR(120),
	FORM_UNIT_DISP VARCHAR(120),
	[ROUTE] VARCHAR(120),
	CONSTRAINT prescription_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.PROCEDURES_ICD (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	SEQ_NUM INT NOT NULL,
	ICD9_CODE VARCHAR(10) NOT NULL,
	CONSTRAINT proceduresicd_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.SERVICES (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	TRANSFER_TIME DATETIME NOT NULL,
	PREV_SERVICE VARCHAR(20),
	CURR_SERVICE VARCHAR(20),
	CONSTRAINT services_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE Clinic.TRANSFERS (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	ICU_STAY_ID INT,
	DB_SOURCE VARCHAR(20),
	EVENT_TYPE VARCHAR(20),
	PREV_CAREUNIT VARCHAR(20),
	CURR_CAREUNIT VARCHAR(20),
	PREV_WARD_ID SMALLINT,
	CURR_WARD_ID SMALLINT,
	IN_TIME DATETIME,
	OUT_TIME DATETIME,
	LOS DOUBLE PRECISION,
	CONSTRAINT transfers_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE ICU.CAREGIVERS (
  	ROW_ID INT NOT NULL,
	CG_ID INT NOT NULL,
	LABEL VARCHAR(15),
	[DESCRIPTION] VARCHAR(30),
	CONSTRAINT cg_rowid_pk PRIMARY KEY (ROW_ID),
	CONSTRAINT cg_cgid_unique UNIQUE (CG_ID)
);

CREATE TABLE ICU.DATETIME_EVENTS (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT,
	ICU_STAY_ID INT,
	ITEM_ID INT NOT NULL,
	CHART_TIME DATETIME NOT NULL,
	STORE_TIME DATETIME NOT NULL,
	CG_ID INT NOT NULL,
	[VALUE] DATETIME,
	VALUE_UOM VARCHAR(50) NOT NULL,
	WARNING SMALLINT,
	ERROR SMALLINT,
	RESULT_STATUS VARCHAR(50),
	[STOPPED] VARCHAR(50),
	CONSTRAINT datetime_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE ICU.D_ITEMS (
  	ROW_ID INT NOT NULL,
	ITEM_ID INT NOT NULL,
	LABEL VARCHAR(200),
	ABBREVIATION VARCHAR(100),
	DB_SOURCE VARCHAR(20),
	LINK_STO VARCHAR(50),
	CATEGORY VARCHAR(100),
	UNIT_NAME VARCHAR(100),
	PARAM_TYPE VARCHAR(30),
	CONCEPT_ID INT,
	CONSTRAINT ditems_itemid_unique UNIQUE (ITEM_ID),
	CONSTRAINT ditems_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE ICU.ICU_STAYS (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	ICU_STAY_ID INT NOT NULL,
	DB_SOURCE VARCHAR(20) NOT NULL,
	FIRST_CARE_UNIT VARCHAR(20) NOT NULL,
	LAST_CARE_UNIT VARCHAR(20) NOT NULL,
	FIRST_WARD_ID SMALLINT NOT NULL,
	LAST_WARD_ID SMALLINT NOT NULL,
	IN_TIME DATETIME NOT NULL,
	OUT_TIME DATETIME,
	LOS DOUBLE PRECISION,
	CONSTRAINT icustay_icustayid_unique UNIQUE (ICU_STAY_ID),
	CONSTRAINT icustay_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE ICU.INPUT_EVENTS_CV (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT,
	ICU_STAY_ID INT,
	CHART_TIME DATETIME,
	ITEM_ID INT,
	AMOUNT DOUBLE PRECISION,
	AMOUNT_UOM VARCHAR(30),
	RATE DOUBLE PRECISION,
	RATE_UOM VARCHAR(30),
	STORE_TIME DATETIME,
	CG_ID INT,
	ORDER_ID INT,
	LINK_ORDER_ID INT,
	[STOPPED] VARCHAR(30),
	NEW_BOTTLE INT,
	ORIGINALA_MOUNT DOUBLE PRECISION,
	ORIGINAL_AMOUNT_UOM VARCHAR(30),
	ORIGINAL_ROUTE VARCHAR(30),
	ORIGINAL_RATE DOUBLE PRECISION,
	ORIGINAL_RATE_UOM VARCHAR(30),
	ORIGINAL_SITE VARCHAR(30),
	CONSTRAINT inputevents_cv_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE ICU.INPUT_EVENTS_MV (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT,
	ICU_STAY_ID INT,
	START_TIME DATETIME,
	END_TIME DATETIME,
	ITEM_ID INT,
	AMOUNT DOUBLE PRECISION,
	AMOUNT_UOM VARCHAR(30),
	RATE DOUBLE PRECISION,
	RATE_UOM VARCHAR(30),
	STORE_TIME DATETIME,
	CG_ID INT,
	ORDER_ID INT,
	LINK_ORDER_ID INT,
	ORDER_CATEGORY_NAME VARCHAR(100),
	SECONDARY_ORDERCATEGORY_NAME VARCHAR(100),
	ORDER_COMPONENT_TYPE_DESCRIPTION VARCHAR(200),
	ORDER_CATEGORY_DESCRIPTION VARCHAR(50),
	PATIENT_WEIGHT DOUBLE PRECISION,
	TOTAL_AMOUNT DOUBLE PRECISION,
	TOTAL_AMOUNT_UOM VARCHAR(50),
	IS_OPEN_BAG SMALLINT,
	CONTINUE_IN_NEXT_DEPT SMALLINT,
	CANCEL_REASON SMALLINT,
	STATUS_DESCRIPTION VARCHAR(30),
	COMMENTS_EDITED_BY VARCHAR(30),
	COMMENTS_CANCELED_BY VARCHAR(40),
	COMMENTS_DATE DATETIME,
	ORIGINAL_AMOUNT DOUBLE PRECISION,
	ORIGINAL_RATE DOUBLE PRECISION,
	CONSTRAINT inputevents_mv_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE ICU.OUTPUT_EVENTS (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT,
	ICU_STAY_ID INT,
	CHART_TIME DATETIME,
	ITEM_ID INT,
	VALUE DOUBLE PRECISION,
	VALUE_UOM VARCHAR(30),
	STORE_TIME DATETIME,
	CG_ID INT,
	[STOPPED] VARCHAR(30),
	NEW_BOTTLE CHAR(1),
	IS_ERROR INT,
	CONSTRAINT outputevents_cv_rowid_pk PRIMARY KEY (ROW_ID)
);

CREATE TABLE ICU.PROCEDURE_EVENTS_MV (
  	ROW_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT NOT NULL,
	ICU_STAY_ID INT,
	START_TIME DATETIME,
	END_TIME DATETIME,
	ITEM_ID INT,
	[VALUE] DOUBLE PRECISION,
	VALUE_UOM VARCHAR(30),
	[LOCATION] VARCHAR(30),
	LOCATION_CATEGORY VARCHAR(30),
	STORE_TIME DATETIME,
	CG_ID INT,
	ORDER_ID INT,
	LINK_ORDER_ID INT,
	ORDER_CATEGORY_NAME VARCHAR(100),
	SECONDARY_ORDER_CATEGORY_NAME VARCHAR(100),
	ORDER_CATEGORY_DESCRIPTION VARCHAR(50),
	IS_OPEN_BAG SMALLINT,
	CONTINUE_IN_NEXT_DEPT SMALLINT,
	CANCEL_REASON SMALLINT,
	STATUS_DESCRIPTION VARCHAR(30),
	COMMENTS_EDITED_BY VARCHAR(30),
	COMMENTS_CANCELED_BY VARCHAR(30),
	COMMENTS_DATE DATETIME,
	CONSTRAINT procedureevents_mv_rowid_pk PRIMARY KEY (ROW_ID)
);
