--- ADMISSIONS ---
CREATE INDEX ADMISSIONS_IDX01
    ON Clinic.ADMISSIONS (SUBJECT_ID);

CREATE INDEX ADMISSIONS_IDX02
    ON Clinic.ADMISSIONS (HADM_ID);

--- CALLOUT ---
CREATE INDEX CALLOUT_IDX01
    ON Clinic.CALLOUT (SUBJECT_ID);

CREATE INDEX CALLOUT_IDX02
    ON Clinic.CALLOUT (HADM_ID);

--- CPT_EVENTS ---
CREATE INDEX CPTEVENTS_idx01
    ON Clinic.CPT_EVENTS (SUBJECT_ID);

CREATE INDEX CPTEVENTS_idx02
    ON Clinic.CPT_EVENTS (CPT_CD);

--- D_ICD_DIAGNOSES ---
CREATE INDEX D_ICD_DIAG_idx01
    ON Clinic.D_ICD_DIAGNOSES (ICD9_CODE);

CREATE INDEX D_ICD_DIAG_idx02
    ON Clinic.D_ICD_DIAGNOSES (LONG_TITLE);

--- D_ICD_PROCEDURES ---
CREATE INDEX D_ICD_PROC_idx01
    ON Clinic.D_ICD_PROCEDURES (ICD9_CODE);

CREATE INDEX D_ICD_PROC_idx02
    ON Clinic.D_ICD_PROCEDURES (LONG_TITLE);

--- D_ITEMS ---
CREATE INDEX D_ITEMS_idx01
    ON ICU.D_ITEMS (ITEM_ID);

CREATE INDEX D_ITEMS_idx02
    ON ICU.D_ITEMS (LABEL);

--- DATETIME_EVENTS ---
CREATE INDEX DATETIMEEVENTS_idx01
    ON ICU.DATETIME_EVENTS (SUBJECT_ID);

CREATE INDEX DATETIMEEVENTS_idx02
    ON ICU.DATETIME_EVENTS (ITEM_ID);

CREATE INDEX DATETIMEEVENTS_idx03
    ON ICU.DATETIME_EVENTS (ICU_STAY_ID);

CREATE INDEX DATETIMEEVENTS_idx04
    ON ICU.DATETIME_EVENTS (HADM_ID);

--- DIAGNOSES_ICD ---
CREATE INDEX DIAGNOSES_ICD_idx01
    ON Clinic.DIAGNOSES_ICD (SUBJECT_ID);

CREATE INDEX DIAGNOSES_ICD_idx02
    ON Clinic.DIAGNOSES_ICD (ICD9_CODE);

CREATE INDEX DIAGNOSES_ICD_idx03
    ON Clinic.DIAGNOSES_ICD (HADM_ID);

--- DRG_CODES ---
CREATE INDEX DRGCODES_idx01
    ON Clinic.DRG_CODES (SUBJECT_ID);

CREATE INDEX DRGCODES_idx02
    ON Clinic.DRG_CODES (DRG_CODE);

CREATE INDEX DRGCODES_idx03
    ON Clinic.DRG_CODES ([DESCRIPTION]);

--- ICU_STAYS ---
CREATE INDEX ICUSTAYS_idx01
    ON ICU.ICU_STAYS (SUBJECT_ID);

CREATE INDEX ICUSTAYS_idx02
    ON ICU.ICU_STAYS (ICU_STAY_ID);

CREATE INDEX ICUSTAYS_IDX06
    ON ICU.ICU_STAYS (HADM_ID);

--- INPUT_EVENTS_CV ---
CREATE INDEX INPUTEVENTS_CV_idx01
    ON ICU.INPUT_EVENTS_CV (SUBJECT_ID);

CREATE INDEX INPUTEVENTS_CV_idx02
    ON ICU.INPUT_EVENTS_CV (HADM_ID);

CREATE INDEX INPUTEVENTS_CV_idx03
    ON ICU.INPUT_EVENTS_CV (ICU_STAY_ID);

CREATE INDEX INPUTEVENTS_CV_idx04
    ON ICU.INPUT_EVENTS_CV (CHART_TIME);

CREATE INDEX INPUTEVENTS_CV_idx05
    ON ICU.INPUT_EVENTS_CV (ITEM_ID);

--- INPUT_EVENTS_MV ---
CREATE INDEX INPUTEVENTS_MV_idx01
    ON ICU.INPUT_EVENTS_MV (SUBJECT_ID);

CREATE INDEX INPUTEVENTS_MV_idx02
    ON ICU.INPUT_EVENTS_MV (HADM_ID);

CREATE INDEX INPUTEVENTS_MV_idx03
    ON ICU.INPUT_EVENTS_MV (ICU_STAY_ID);

CREATE INDEX INPUTEVENTS_MV_idx05
    ON ICU.INPUT_EVENTS_MV (ITEM_ID);

--- MICROBIOLOGY_EVENTS ---
CREATE INDEX MICROBIOLOGYEVENTS_idx01
    ON Clinic.MICROBIOLOGY_EVENTS (SUBJECT_ID);

CREATE INDEX MICROBIOLOGYEVENTS_idx02
    ON Clinic.MICROBIOLOGY_EVENTS (HADM_ID);

--- OUTPUT_EVENTS ---
CREATE INDEX OUTPUTEVENTS_idx01
    ON ICU.OUTPUT_EVENTS (SUBJECT_ID);

CREATE INDEX OUTPUTEVENTS_idx02
    ON ICU.OUTPUT_EVENTS (ITEM_ID);

CREATE INDEX OUTPUTEVENTS_idx03
    ON ICU.OUTPUT_EVENTS (ICU_STAY_ID);

CREATE INDEX OUTPUTEVENTS_idx04
    ON ICU.OUTPUT_EVENTS (HADM_ID);

--- PRESCRIPTIONS ---
CREATE INDEX PRESCRIPTIONS_idx01
    ON Clinic.PRESCRIPTIONS (SUBJECT_ID);

CREATE INDEX PRESCRIPTIONS_idx02
    ON Clinic.PRESCRIPTIONS (ICU_STAY_ID);

CREATE INDEX PRESCRIPTIONS_idx03
    ON Clinic.PRESCRIPTIONS (DRUG_TYPE);

CREATE INDEX PRESCRIPTIONS_idx04
    ON Clinic.PRESCRIPTIONS (DRUG);

CREATE INDEX PRESCRIPTIONS_idx05
    ON Clinic.PRESCRIPTIONS (HADM_ID);

--- PROCEDURE_EVENTS_MV ---
CREATE INDEX PROCEDUREEVENTS_MV_idx01
    ON ICU.PROCEDURE_EVENTS_MV (SUBJECT_ID);

CREATE INDEX PROCEDUREEVENTS_MV_idx02
    ON ICU.PROCEDURE_EVENTS_MV (HADM_ID);

CREATE INDEX PROCEDUREEVENTS_MV_idx03
    ON ICU.PROCEDURE_EVENTS_MV (ICU_STAY_ID);

CREATE INDEX PROCEDUREEVENTS_MV_idx05
    ON ICU.PROCEDURE_EVENTS_MV (ITEM_ID);

--- PROCEDURES_ICD ---
CREATE INDEX PROCEDURES_ICD_idx01
    ON Clinic.PROCEDURES_ICD (SUBJECT_ID);

CREATE INDEX PROCEDURES_ICD_idx02
    ON Clinic.PROCEDURES_ICD (ICD9_CODE);

CREATE INDEX PROCEDURES_ICD_idx03
    ON Clinic.PROCEDURES_ICD (HADM_ID);

--- SERVICES ---
CREATE INDEX SERVICES_idx01
    ON Clinic.[SERVICES] (SUBJECT_ID);

CREATE INDEX SERVICES_idx02
    ON Clinic.[SERVICES] (HADM_ID);

--- TRANSFERS ---
CREATE INDEX TRANSFERS_idx01
    ON Clinic.TRANSFERS (SUBJECT_ID);

CREATE INDEX TRANSFERS_idx02
    ON Clinic.TRANSFERS (ICU_STAY_ID);

CREATE INDEX TRANSFERS_idx03
    ON Clinic.TRANSFERS (HADM_ID);
